# Write a class NeuralNetwork that defines a neural network with one hidden layer performing binary classification

* class constructor: def __init__(self, nx, nodes):
- nx is the number of input features
If nx is not an integer, raise a TypeError with the exception: nx must be an integer
If nx is less than 1, raise a ValueError with the exception: nx must be a positive integer
* nodes is the number of nodes found in the hidden layer
If nodes is not an integer, raise a TypeError with the exception: nodes must be an integer
If nodes is less than 1, raise a ValueError with the exception: nodes must be a positive integer
- Public instance attributes:
W1: The weights vector for the hidden layer. Upon instantiation, it should be initialized using a random normal distribution.
b1: The bias for the hidden layer. Upon instantiation, it should be initialized with 0’s.
A1: The activated output for the hidden layer. Upon instantiation, it should be initialized to 0.
W2: The weights vector for the output neuron. Upon instantiation, it should be initialized using a random normal distribution.
b2: The bias for the output neuron. Upon instantiation, it should be initialized to 0.
A2: The activated output for the output neuron (prediction). Upon instantiation, it should be initialized to 0.

In [1]:
#!/usr/bin/env python3
"""
A neural network with one hidden layer performing binary classification
"""

import numpy as np


class NeuralNetwork:
    """
    A neural network with one hidden layer performing binary classification
    """
    def __init__(self, nx, nodes):
        """
        nx is the number of input features
        
        nodes is the number of nodes in the hidden layer
        
        """
        self.nodes = nodes
        self.nx = nx
        if not isinstance(nx, int):
            raise TypeError('nx must be an integer')
        if nx < 1:
            raise ValueError('nx must be a positive integer')
        if not isinstance(nodes, int):
            raise TypeError('nodes must be an integer')
        if nodes < 1:
            raise ValueError('nodes must be a positive integer')
        
        self.W1 = np.random.randn(nx, nodes)
        self.W2 = np.random.randn(1, nodes)
        self.b1 = np.zeros((1, nodes))
        self.b2 = 0
        self.A1 = 0
        self.A2 = 0


In [4]:
# Main func

NN = NeuralNetwork

lib_train = np.load('../data/Binary_Train.npz')
X_3D, Y = lib_train['X'], lib_train['Y']
X = X_3D.reshape((X_3D.shape[0], -1)).T

np.random.seed(0)
nn = NN(X.shape[0], 3)
print(nn.W1)
print(nn.W1.shape)
print(nn.b1)
print(nn.W2)
print(nn.W2.shape)
print(nn.b2)
print(nn.A1)
print(nn.A2)
nn.A1 = 10
print(nn.A1)


[[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]
 [ 0.95008842 -0.15135721 -0.10321885]
 ...
 [ 0.86214806 -0.11858662  0.48837059]
 [ 0.96593612  1.42260475  1.96122699]
 [-0.07223876  0.31112445 -1.07836109]]
(784, 3)
[[0. 0. 0.]]
[[ 1.06160017 -1.18488744 -1.80525169]]
(1, 3)
0
0
0
10
